#!/usr/bin/env node
/**
 * Generates src/fonts.ts by scanning the actual figlet importable-fonts directory
 * and src/cfonts-data.ts by extracting cfonts font JSON data.
 */
const fs = require('fs');
const path = require('path');

// ─── Figlet Fonts ───
const figletDir = path.join(__dirname, '..', 'node_modules', 'figlet', 'importable-fonts');
const figletFiles = fs.readdirSync(figletDir)
  .filter(f => f.endsWith('.js') && !f.endsWith('.d.ts'))
  .map(f => f.replace(/\.js$/, ''))
  .sort((a, b) => a.localeCompare(b));

console.log(`Found ${figletFiles.length} figlet fonts`);

// Featured fonts (hand-picked popular ones)
const FEATURED = [
  "Standard", "Big", "Slant", "Banner", "3D-ASCII", "ANSI Shadow",
  "Block", "Doom", "Epic", "Graffiti", "Isometric1", "Star Wars",
  "Bloody", "Cards", "Doh", "Ghost", "Ogre", "Small", "Speed",
  "Sub-Zero", "Rectangles", "Calvin S", "Colossal", "Alpha",
];

// Validate featured fonts exist
const validFeatured = FEATURED.filter(f => figletFiles.includes(f));

const fontsTs = `// Auto-generated by scripts/generate-fonts.cjs — DO NOT EDIT MANUALLY
// Total: ${figletFiles.length} FIGlet fonts

export const FIGLET_FONT_NAMES = [
${figletFiles.map(f => `  "${f}",`).join('\n')}
] as const;

export type FigletFontName = typeof FIGLET_FONT_NAMES[number];

// Featured/popular fonts shown first
export const FEATURED_FONTS: FigletFontName[] = [
${validFeatured.map(f => `  "${f}",`).join('\n')}
];
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'assets', 'fonts.ts'), fontsTs);
console.log(`✓ Wrote src/fonts.ts with ${figletFiles.length} figlet fonts`);

// ─── cfonts Data ───
const cfontsDir = path.join(__dirname, '..', 'node_modules', 'cfonts', 'fonts');
const cfontNames = fs.readdirSync(cfontsDir)
  .filter(f => f.endsWith('.json'))
  .map(f => f.replace(/\.json$/, ''))
  .sort();

console.log(`Found ${cfontNames.length} cfonts fonts`);

const fontDataEntries = cfontNames.map(name => {
  const data = JSON.parse(fs.readFileSync(path.join(cfontsDir, `${name}.json`), 'utf8'));
  return `  "${name}": ${JSON.stringify(data)},`;
});

const cfontsDataTs = `// Auto-generated by scripts/generate-fonts.cjs — DO NOT EDIT MANUALLY
// Total: ${cfontNames.length} cfonts fonts

export const CFONTS_NAMES = [
${cfontNames.map(f => `  "${f}",`).join('\n')}
] as const;

export type CfontName = typeof CFONTS_NAMES[number];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const CFONTS_DATA: Record<string, any> = {
${fontDataEntries.join('\n')}
};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'assets', 'cfonts-data.ts'), cfontsDataTs);
console.log(`✓ Wrote src/cfonts-data.ts with ${cfontNames.length} cfonts fonts`);

console.log(`\n📊 Total: ${figletFiles.length} figlet + ${cfontNames.length} cfonts = ${figletFiles.length + cfontNames.length} fonts`);

